ProjectPOS.Web/Controllers/JsonController.cs
using MiniProjectPOS.DAL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProjectPOS.Web.Controllers
{
    public class JsonController : Controller
    {
        // GET: Json
        public ActionResult Index()
        {
            return View();
        }

        public JsonResult GetAllProv()
        {
            return Json(ProvinceDAL.GetAll(), JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetRegionByProv(int? id)
        {
            return Json(RegionDAL.GetByProvinceId(id), JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetDistrictByRegion(int? id)
        {
            return Json(DistrictDAL.GetByRegionId(id), JsonRequestBehavior.AllowGet);
        }
    }
}

ProjectPOS.Web/Controllers/OutletController.cs
using MiniProjectPOS.DAL;
using MiniProjectPOS.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProjectPOS.Web.Controllers
{
    public class OutletController : Controller
    {
        // GET: Outlet
        public ActionResult Index()
        {
            return View(OutletDAL.GetAll());
        }

        public ActionResult Search(string strSearch) 
        {
            return PartialView("List", OutletDAL.GetAllBySearch(strSearch));
        }

        public ActionResult Create()
        {
            ViewBag.ProvinceList = new SelectList(ProvinceDAL.GetAll(), "ID", "ProvinceName");
            return PartialView("Create");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(OutletViewModel model)
        {
            if (ModelState.IsValid)
            {
                if (OutletDAL.Add(model))
                {
                    return RedirectToAction("Index");
                }
            }
            ViewBag.ProvinceList = new SelectList(ProvinceDAL.GetAll(), "ID", "ProvinceName");
            return PartialView("Create", model);
        }

        public ActionResult Edit(int id)
        {
            OutletViewModel model = OutletDAL.GetById(id);
            ViewBag.ProvinceList = new SelectList(ProvinceDAL.GetAll(), "ID", "ProvinceName");
            ViewBag.RegionList = new SelectList(RegionDAL.GetByProvinceId(model.ProvinceID), "ID", "RegionName");
            ViewBag.DistrictList = new SelectList(DistrictDAL.GetByRegionId(model.RegionID), "ID", "DistrictName");
            return PartialView("Edit", model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(OutletViewModel model)
        {
            if (ModelState.IsValid)
            {
                if (OutletDAL.Update(model))
                {
                    return RedirectToAction("Index");
                }
            }
            ViewBag.ProvinceList = new SelectList(ProvinceDAL.GetAll(), "ID", "ProvinceName");
            return PartialView("Edit", model);
        }

        public ActionResult Delete(int id)
        {
            return PartialView("Delete", OutletDAL.GetById(id));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(SupplierViewModel model)
        {
            if (ModelState.IsValid)
            {
                if (OutletDAL.Delete(model.ID))
                {
                    return RedirectToAction("Index");
                }
            }
            return PartialView("Delete", model);
        }
    }
}

ProjectPOS.Web/Views/Outlet/Create.cshtml
@model MiniProjectPOS.ViewModel.OutletViewModel

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.OutletName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OutletName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OutletName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProvinceID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.ProvinceID, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.DropDownListFor(model => model.ProvinceID, (IEnumerable<SelectListItem>)ViewBag.ProvinceList, "Select Province", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ProvinceID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RegionID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.RegionID, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.DropDownListFor(model => model.RegionID, new SelectList(String.Empty, "Value", "Text"), "Select Region", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.RegionID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DistrictID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.DistrictID, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.DropDownListFor(model => model.DistrictID, new SelectList(String.Empty, "Value", "Text"), "Select District", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.DistrictID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PostalCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PostalCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PostalCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="modal-footer">
            <button type="button" class="btn btn-pop btn-default" data-dismiss="modal">Pop</button>
            <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
            <button type="submit" class="btn btn-primary">Save</button>
        </div>

    </div>
}
@section Scripts{
    @Scripts.Render("~/bundles/jqueryval")
}

<script type="text/javascript">
    $("#ProvinceID").change(function () {
        $.ajax({
            url: '@Url.Action("GetRegionByProv", "Json")',
            data: { id: $(this).val() },
            dataType: 'JSON',
            type: 'get',
            success: function (listItem) {
                ResetDropDown(1);
                $.each(listItem, function (index, item) {
                    $("#RegionID").append('<option value="' + item.ID + '">' + item.RegionName + '</option>');
                });
            }
        });
    });

    $("#RegionID").change(
        function () {
            $.ajax({
                url: '@Url.Action("GetDistrictByRegion", "Json")',
                data: { id: $(this).val() },
                dataType: 'JSON',
                type: 'get',
                success: function (listItem) {
                    ResetDropDown(2);
                    $.each(listItem, function (index, item) {
                        $("#DistrictID").append('<option value="' + item.ID + '">' + item.DistrictName + '</option>');
                    });
                }
            });
        });

    function ResetDropDown(level) {
        if (level <= 1) {
            $("#RegionID").empty();
            $("#RegionID").append('<option value="">Select Kota</option>');
        }

        if (level <= 2) {
            $("#DistrictID").empty();
            $("#DistrictID").append('<option value="">Select Kecamatan</option>');
        }
    }

    $(".btn-pop").click(function () {
        $("#modal-form-2").modal("show");
    });


</script>

ProjectPOS.Web/Views/Outlet/Delete.cshtml
@model MiniProjectPOS.ViewModel.OutletViewModel

<h5>Are you sure you want to delete this?</h5>
<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.OutletName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OutletName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProvinceName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProvinceName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RegionName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RegionName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DistrictName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DistrictName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PostalCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PostalCode)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()
        <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
            <button type="submit" class="btn btn-primary">Delete</button>
        </div>
    }
</div>

ProjectPOS.Web/Views/Outlet/Edit.cshtml
@model MiniProjectPOS.ViewModel.OutletViewModel


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.OutletName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OutletName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OutletName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProvinceID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.ProvinceID, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.DropDownListFor(model => model.ProvinceID, (IEnumerable<SelectListItem>)ViewBag.ProvinceList, "Select Province", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ProvinceID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RegionID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.RegionID, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.DropDownListFor(model => model.RegionID, (IEnumerable<SelectListItem>)ViewBag.RegionList, "Select Region", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.RegionID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DistrictID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.DistrictID, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.DropDownListFor(model => model.DistrictID, (IEnumerable<SelectListItem>)ViewBag.DistrictList, "Select District", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.DistrictID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PostalCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PostalCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PostalCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
            <button type="submit" class="btn btn-primary">Save</button>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

<script type="text/javascript">
    $("#ProvinceID").change(function () {
        $.ajax({
            url: '@Url.Action("GetRegionByProv", "Json")',
            data: { id: $(this).val() },
            dataType: 'JSON',
            type: 'get',
            success: function (listItem) {
                ResetDropDown(1);
                $.each(listItem, function (index, item) {
                    $("#RegionID").append('<option value="' + item.ID + '">' + item.RegionName + '</option>');
                });
            }
        });
    });

    $("#RegionID").change(
        function () {
            $.ajax({
                url: '@Url.Action("GetDistrictByRegion", "Json")',
                data: { id: $(this).val() },
                dataType: 'JSON',
                type: 'get',
                success: function (listItem) {
                    ResetDropDown(2);
                    $.each(listItem, function (index, item) {
                        $("#DistrictID").append('<option value="' + item.ID + '">' + item.DistrictName + '</option>');
                    });
                }
            });
        });

    function ResetDropDown(level) {
        if (level <= 1) {
            $("#RegionID").empty();
            $("#RegionID").append('<option value="">Select Kota</option>');
        }

        if (level <= 2) {
            $("#DistrictID").empty();
            $("#DistrictID").append('<option value="">Select Kecamatan</option>');
        }
    }
</script>

ProjectPOS.Web/Views/Outlet/Index.cshtml
@model IEnumerable<MiniProjectPOS.ViewModel.OutletViewModel>

@{
    ViewBag.Title = "Outlet";
}

<h2>@ViewBag.Title</h2>
<div class="row">
    <div class="col-sm-6">
        <div class="input-group">
            <input id="index-search" type="text" style="max-width: 100%;" class="form-control" placeholder="Find outlet...">
            <span class="input-group-btn">
                <button class="btn btn-default btn-search" type="button"><span class="glyphicon glyphicon-search" aria-hidden="true"></span></button>
            </span>
        </div><!-- /input-group -->
    </div>
    <div class="col-sm-6">
        <button type="button" id="btn-add" class="btn btn-primary">Create</button>
    </div>
</div>
<hr />
<div id="TableList">
</div>
<div id="modal-form" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Supplier</h4>
            </div>
            <div class="modal-body">
                <p>One fine body&hellip;</p>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<div id="modal-form-2" class="modal fade" tabindex="-100" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Supplier</h4>
            </div>
            <div class="modal-body-2">
                <div class="modal-footer">
                    <button type="button" class="btn btn-isi btn-default">Isi value</button>
                    <button type="button" class="btn btn-pop-2 btn-default" data-dismiss="modal">Cancel</button>
                    <button type="button" class="btn btn-pop-2 btn-primary" data-dismiss="modal">Save</button>
                </div>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

@section Scripts{

    <script type="text/javascript">
        $(document).ready(function () {
            searchDefault();
        });

        $(".btn-search").click(function () {
            searchDefault();
        });

        function searchDefault() {
            var textSearch = $("#index-search").val();
            $.ajax({
                url: '@Url.Action("Search", "Outlet")',
                data: { strSearch: textSearch },
                type: 'get',
                success: function (result) {
                    $("#TableList").html(result);
                }
            });
        }

        $("#btn-add").click(function () {
            $.ajax({
                url: '@Url.Action("Create", "Outlet")',
                type: 'get',
                success: function (result) {
                    $(".modal-body").html(result);
                    $("#modal-form").modal("show");
                }
            });
        });


        $(".btn-pop-2").click(function () {
            $("#modal-form").modal("show");
        });

        $(".btn-isi").click(function () {
            $("#OutletName").val('Inputan dari pop up');
        });
    </script>
}

ProjectPOS.Web/Views/Outlet/List.cshtml
@using ProjectPOS.Web.Security
@model IEnumerable<MiniProjectPOS.ViewModel.OutletViewModel>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.OutletName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Address)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Phone)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ProvinceName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RegionName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DistrictName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PostalCode)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.OutletName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Phone)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.ProvinceName)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.RegionName)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.DistrictName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PostalCode)
            </td>
            <td>
                <div class="btn-group btn-group-sm btn-group-solid">
                    @{if (SessionPersister.Username == "admin")
                    {
                        <button type="button" class="btn btn-action btn-edit btn-warning" data-id="@item.ID"><span class="glyphicon glyphicon-edit" aria-hidden="true"></span></button>
                    }}
                    <button type="button" class="btn btn-action btn-details btn-success" data-id="@item.ID"><span class="glyphicon glyphicon-th-list" aria-hidden="true"></span></button>
                    <button type="button" class="btn btn-action btn-delete btn-danger" data-id="@item.ID"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span></button>
                </div>
            </td>
        </tr>
    }

</table>

<script type="text/javascript">
    $(".btn-edit").click(
        function () {
            var vid = $(this).attr("data-id");
            $.ajax({
                url: '@Url.Action("Edit", "Outlet")',
                data: { id: vid },
                type: 'get',
                success: function (result) {
                    $(".modal-body").html(result);
                    $("#modal-form").modal("show");
                }
            });
        }
    );

    $(".btn-delete").click(
            function () {
                var vid = $(this).attr("data-id");
                $.ajax({
                    url: '@Url.Action("Delete", "Outlet")',
                    data: { id: vid },
                    type: 'get',
                    success: function (result) {
                        $(".modal-body").html(result);
                        $("#modal-form").modal("show");
                    }
                });
            }
        );
</script>