ProjectPOS.Web/Controllers/ItemsController.cs
using MiniProjectPOS.DAL;
using MiniProjectPOS.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProjectPOS.Web.Controllers
{
    public class ItemsController : Controller
    {
        // GET: Item
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Search() 
        {
            return PartialView("List", ItemsDAL.GetAll());
        }

        public ActionResult Create() 
        {
            ViewBag.ListCategory = new SelectList(CategoryDAL.GetAll(), "ID", "Name");
            return PartialView();
        }

        public ActionResult ItemVarians()
        {
            List<ItemsVariantViewModel> model = new List<ItemsVariantViewModel>();
            return PartialView("ItemVarians", model);
        }

        public ActionResult Edit(int id)
        {
            ViewBag.ListCategory = new SelectList(CategoryDAL.GetAll(), "ID", "Name");
            return PartialView("Edit", ItemsDAL.GetById(id));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ItemsViewModel model) 
        {
            if (ModelState.IsValid)
            {
                if (ItemsDAL.Edit(model))
                {
                    return RedirectToAction("Index");
                }
            }
            else
            {
                var errors = ModelState.Values.SelectMany(v => v.Errors);
            }
            return View("Index");
        }

        public ActionResult AddVariant() 
        {
            return PartialView();
        }

        public ActionResult AddInventory() {
            return PartialView();
        }

        [HttpPost]
        //[AllowAnonymous]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ItemsViewModel model)
        {
            if (ModelState.IsValid)
            {
                if (ItemsDAL.Add(model))
                {
                    return RedirectToAction("Index");
                }
            }
            return PartialView("Create", model);
        }
    }
}

ProjectPOS.Web/Views/Items/AddInventory.cshtml
<tr data-id="">
    <td>
        <input data-val="true" data-val-number="The field ID must be a number." data-val-required="The ID field is required." id="ItemVarians_0__Invents_ID" name="ItemVarians[0].Invents.ID" value="0" type="hidden">
        <input class="form-control text-box single-line" id="ItemVarians_0__Invents_VariantName" name="ItemVarians[0].Invents.VariantName" value="" type="text" readonly>
    </td>
    <td><input class="form-control text-box single-line" data-val="true" data-val-number="The field InStock must be a number." id="ItemVarians_0__Invents_InStock" name="ItemVarians[0].Invents.InStock" value="" type="number"></td>
    <td><input class="form-control text-box single-line" data-val="true" data-val-number="The field AlertAt must be a number." id="ItemVarians_0__Invents_AlertAt" name="ItemVarians[0].Invents.AlertAt" value="" type="number"></td>
</tr>

ProjectPOS.Web/Views/Items/AddVariant.cshtml
<tr data-id="">
    <td>
        <input data-val="true" data-val-number="The field ID must be a number." data-val-required="The ID field is required." id="ItemVarians_0__ID" name="ItemVarians[0].ID" value="0" type="hidden">
        <input class="form-control text-box single-line" id="ItemVarians_0__VariantName" name="ItemVarians[0].VariantName" onkeyup="BindWithInventory(this)" value="" type="text">
    </td>
    <td><input class="form-control text-box single-line" id="ItemVarians_0__SKU" name="ItemVarians[0].SKU" value="" type="text"></td>
    <td><input class="form-control text-box single-line" data-val="true" data-val-number="The field Price must be a number." id="ItemVarians_0__Price" name="ItemVarians[0].Price" value="" type="text"></td>
    <td>
        <input data-val="true" data-val-required="The RecStatus field is required." id="ItemVarians_0__RecStatus" name="ItemVarians[0].RecStatus" value="1" type="hidden">
        <button type="button" class="btn btn-del-var btn-danger" onclick="RemoveRow($(this).closest('tr').index())"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span></button>
    </td>
</tr>

ProjectPOS.Web/Views/Items/Create.cshtml
@model MiniProjectPOS.ViewModel.ItemsViewModel

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Create</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CategoryID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.CategoryID, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.DropDownListFor(model => model.CategoryID, (IEnumerable<SelectListItem>)ViewBag.ListCategory, "Select Category", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CategoryID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <table id="TableVariant">
            </table>
        </div>

        <button type="button" class="btn btn-add-variant btn-success">Add Variant</button>
        <hr />

        <div class="form-group">
            <table id="TableInventory">
            </table>
        </div>

        <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
            <button type="submit" class="btn btn-save btn-primary">Save</button>
            @*<button id="btn-save-item" type="button" class="btn btn-primary">Save</button>*@
        </div>

    </div>
}

<script type="text/javascript">
    $(document).ready(function () {
        AddVariant();
    });

    function GetItemVariants() {
        $.ajax({
            url: '@Url.Action("ItemVarians", "Items")',
            type: 'get',
            success: function (result) {
                $("#TableVariant").html(result);
            }
        });
    }

    $(".btn-add-variant").click(function () {
        AddVariant();
    });

    $("#btn-save-item").click(function () {
        var parent = { ID: null, Name: $("#Name").val(), CategoryID: $("#CategoryID").val(), ItemVarians: null };

        var ListVarians = [];
        var Variant = { ID: null, VariantName: null, SKU: null, Price: null, Invents: null };

        var valInput = "";

        var rowCount = $('#TableVariant tr').length;
        if (rowCount > 0) {
            $.each($("#TableVariant").find("tr"), function (i, val) {
                var varName = $(this).find(":input[name='variant-name']").val();
                var varSKU = $(this).find(":input[name='variant-sku']").val();
                var varPrice = $(this).find(":input[name='variant-price']").val();

                varPrice = parseFloat(Number(varPrice.replace(/[^0-9\.]+/g, "")));
                Variant = { ID: null, VariantName: varName, SKU: varSKU, Price: varPrice };
                ListVarians.push(Variant);
            });
        }

        //var ListInvents = [];
        var Invent = { ID: null, InStock: null, AlertAt: null };

        rowCount = $('#TableInventory tr').length;
        if (rowCount > 0) {
            var counter = 0;
            $.each($("#TableInventory").find("tr"), function (i, val) {
                var varInStock = $(this).find(":input[name='invent-instock']").val();
                var varAlertAt = $(this).find(":input[name='invent-alert']").val();
                
                varInStock = parseFloat(Number(varInStock.replace(/[^0-9\.]+/g, "")));
                varAlertAt = parseFloat(Number(varAlertAt.replace(/[^0-9\.]+/g, "")));

                Invent = { ID: null, InStock: varInStock, AlertAt: varAlertAt };
                ListVarians[counter].Invents = Invent;
                counter += 1;
                //ListInvents.push(Invent);
            });
        }

        parent.ItemVarians = ListVarians;

        //parent.ItemInvents = ListInvents;
        //alert(JSON.stringify(parent));
        $.ajax({
            url: '@Url.Action("Create", "Items")',
            data: JSON.stringify(parent),
            type: 'post',
            contentType: 'application/json; charset=utf-8',
            success: function (result) {
                //alert(result);
                //initializePage();
            }
        });
    });

    
</script>

ProjectPOS.Web/Views/Items/Edit.cshtml
@model MiniProjectPOS.ViewModel.ItemsViewModel

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h5>Edit</h5>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CategoryID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.CategoryID, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.DropDownListFor(model => model.CategoryID, (IEnumerable<SelectListItem>)ViewBag.ListCategory, "Select Category", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CategoryID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <table id="TableVariant">
                @for (int I = 0; I < Model.ItemVarians.Count; I++)
                {
                    <tr>
                        <td>
                            @Html.HiddenFor(X => X.ItemVarians[I].ID)
                            @Html.EditorFor(X => X.ItemVarians[I].VariantName, new { htmlAttributes = new { @onkeyup = "BindWithInventory(this)", @class = "form-control" } })
                        </td>
                        <td>
                            @Html.EditorFor(X => X.ItemVarians[I].SKU, new { htmlAttributes = new { @class = "form-control" } })
                        </td>
                        <td>
                            @Html.EditorFor(X => X.ItemVarians[I].Price, new { htmlAttributes = new { @class = "form-control" } })
                        </td>
                        <td>
                            @Html.HiddenFor(X => Model.ItemVarians[I].RecStatus)
                        <button type="button" class="btn btn-del-var btn-danger" onclick="RemoveRow(this)"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span></button></td>
                    </tr>
                }
            </table>
        </div>

        <button type="button" class="btn btn-add-variant btn-success">Add Variant</button>

        <div class="form-group">
            <table id="TableInventory">
                @for (int I = 0; I < Model.ItemVarians.Count; I++)
                {
                    <tr>
                        <td>
                            @Html.HiddenFor(X => X.ItemVarians[I].Invents.ID)
                            @Html.EditorFor(X => X.ItemVarians[I].Invents.VariantName, new { htmlAttributes = new { @class = "form-control", disabled = "disabled", @readonly = "readonly" }})
                        </td>
                        <td>
                            @Html.EditorFor(X => X.ItemVarians[I].Invents.InStock, new { htmlAttributes = new { @class = "form-control" } })
                        </td>
                        <td>
                            @Html.EditorFor(X => X.ItemVarians[I].Invents.AlertAt, new { htmlAttributes = new { @class = "form-control" } })
                        </td>
                    </tr>
                }
            </table>
        </div>

        <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
            <button type="submit" class="btn btn-save btn-primary">Save</button>
        </div>
    </div>
}

<script type="text/javascript">
    $(document).ready(function () {
        var rowCount = $('#TableVariant tr').length;
        if (rowCount == 0) {
            AddVariant();
        }
    });

    function GetItemVariants() {
        $.ajax({
            url: '@Url.Action("ItemVarians", "Items")',
            type: 'get',
            success: function (result) {
                $("#TableVariant").html(result);
            }
        });
    }

    $(".btn-add-variant").click(function () {
        AddVariant();
    });
</script>

ProjectPOS.Web/Views/Items/Index.cshtml
@{
    ViewBag.Title = "Items";
}

<h2>@ViewBag.Title</h2>
<div class="row">
    <div class="col-sm-6">
        <div class="input-group">
            <input id="index-search" type="text" style="max-width: 100%;" class="form-control" placeholder="Find category...">
            <span class="input-group-btn">
                <button class="btn btn-default btn-search" type="button"><span class="glyphicon glyphicon-search" aria-hidden="true"></span></button>
            </span>
        </div><!-- /input-group -->
    </div>
    <div class="col-sm-6">
        <button type="button" id="btn-add" class="btn btn-primary">Create</button>
    </div>
</div>
<hr />
<div id="TableList">
</div>

<div id="modal-form" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Items</h4>
            </div>
            <div class="modal-body">
                <p>One fine body&hellip;</p>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

@section Scripts{
    <script type="text/javascript">
    $(document).ready(function () {
        SearchDefault();
    });

    function SearchDefault() {
        var textSearch = $("#index-search").val();
        $.ajax({
            url: '@Url.Action("Search", "Items")',
            data: { strSearch: textSearch },
            type: 'get',
            success: function (result) {
                $("#TableList").html(result);
            }
        });
    }

        $("#btn-add").click(function () {
            $.ajax({
                url: '@Url.Action("Create", "Items")',
                type: 'get',
                contentType: 'html',
                success: function (result) {
                    $(".modal-body").html(result);
                    $("#modal-form").modal("show");
                }
            });
        });

        function AddVariant() {
            $.ajax({
                url: '@Url.Action("AddVariant", "Items")',
                type: 'get',
                dataType: 'html',
                success: function (result) {
                    $("#TableVariant").append(result);
                    initializePage();
                }
            });

            $.ajax({
                url: '@Url.Action("AddInventory", "Items")',
                type: 'get',
                dataType: 'html',
                success: function (result) {
                    $("#TableInventory").append(result);
                    initializePage();
                }
            });

            setTimeout(function () {
                RefactorName();
            }, 1000);
        }

        function RemoveRow(obj) {
            $(obj).closest('tr').hide();
            $(obj).prev('input').val('-1');
            var idx = $(obj).closest('tr').index();
            $("#TableInventory tr:eq(" + idx + ")").hide();
            setTimeout(function () {
                RefactorName();
            }, 1000);

            //$('<div></div>').appendTo('body')
            //    .html('<div><h6>Are you sure?</h6></div>')
            //    .dialog({
            //        modal: true,
            //        title: 'Delete message',
            //        zIndex: 10000,
            //        autoOpen: true,
            //        width: 'auto',
            //        resizable: false,
            //        buttons: {
            //            Yes: function () {
            //                $(this).dialog("close");
            //            },
            //            No: function () {
            //                $(this).dialog("close");
            //            }
            //        },
            //        close: function (event, ui) {
            //            $(this).remove();
            //        }
            //    });
        }

        function RefactorName() {

            var rowCount = $('#TableVariant tr').length;
            if (rowCount > 0) {
                var idx = 0;
                $.each($("#TableVariant").find("tr"), function (i, val) {
                    var varID = $(this).find(":input[name*='.ID']");
                    var varName = $(this).find(":input[name*='.VariantName']");
                    var varSKU = $(this).find(":input[name*='.SKU']");
                    var varPrice = $(this).find(":input[name*='.Price']");
                    var varRecStatus = $(this).find(":input[name*='.RecStatus']");

                    $(varID).attr("id", varID.attr("id").replace(/\_.*?\__\s?/g, "_" + idx + "__"));
                    $(varName).attr("id", varName.attr("id").replace(/\_.*?\__\s?/g, "_" + idx + "__"));
                    $(varSKU).attr("id", varSKU.attr("id").replace(/\_.*?\__\s?/g, "_" + idx + "__"));
                    $(varPrice).attr("id", varPrice.attr("id").replace(/\__.*?\_\s?/g, "_" + idx + "__"));
                    $(varRecStatus).attr("id", varRecStatus.attr("id").replace(/\__.*?\_\s?/g, "_" + idx + "__"));

                    $(varID).attr("name", varID.attr("name").replace(/\[.*?\]\s?/g, "[" + idx + "]"));
                    $(varName).attr("name", varName.attr("name").replace(/\[.*?\]\s?/g, "[" + idx + "]"));
                    $(varSKU).attr("name", varSKU.attr("name").replace(/\[.*?\]\s?/g, "[" + idx + "]"));
                    $(varPrice).attr("name", varPrice.attr("name").replace(/\[.*?\]\s?/g, "[" + idx + "]"));
                    $(varRecStatus).attr("name", varRecStatus.attr("name").replace(/\[.*?\]\s?/g, "[" + idx + "]"));
                    idx += 1;
                });
            }

            rowCount = $('#TableInventory tr').length;
            if (rowCount > 0) {
                var idx = 0;
                $.each($("#TableInventory").find("tr"), function (i, val) {
                    var varVarName = $(this).find(":input[name*='.Invents.VariantName']");
                    var varInStock = $(this).find(":input[name*='.Invents.InStock']");
                    var varAlertAt = $(this).find(":input[name*='.Invents.AlertAt']");

                    $(varVarName).attr("id", varVarName.attr("id").replace(/\_.*?\__\s?/g, "_" + idx + "__"));
                    $(varInStock).attr("id", varInStock.attr("id").replace(/\_.*?\__\s?/g, "_" + idx + "__"));
                    $(varAlertAt).attr("id", varAlertAt.attr("id").replace(/\_.*?\__\s?/g, "_" + idx + "__"));

                    $(varVarName).attr("name", varVarName.attr("name").replace(/\[.*?\]\s?/g, "[" + idx + "]"));
                    $(varInStock).attr("name", varInStock.attr("name").replace(/\[.*?\]\s?/g, "[" + idx + "]"));
                    $(varAlertAt).attr("name", varAlertAt.attr("name").replace(/\[.*?\]\s?/g, "[" + idx + "]"));
                    idx += 1;
                });
            }

        }

        function BindWithInventory(x) {
            var vVal = $(x).val();
            var idx = $(x).closest('tr').index();
            var tr = $("#TableInventory tr:eq(" + idx + ")");
            var varVarName = tr.find(":input[name*='.Invents.VariantName']");
            varVarName.val(vVal);
            //alert(varVarName.val());
            //var td = $(tr).children().eq(0);
            //var input = $(td).children().eq(0);
            //$(".input-inv-name").val(val);
        }

    </script>
}

ProjectPOS.Web/Views/Items/ItemVarians.cshtml
@model IEnumerable<MiniProjectPOS.ViewModel.ItemsVariantViewModel>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.VariantName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SKU)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.VariantName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SKU)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Price)
        </td>
    </tr>
}
    <tr>
        <td colspan="3">
            <button type="button" class="btn btn-action btn-manage btn-warning"><span class="glyphicon glyphicon-edit" aria-hidden="true"></span></button>
        </td>
    </tr>
</table>

ProjectPOS.Web/Views/Items/List.cshtml
@model IEnumerable<MiniProjectPOS.ViewModel.ItemsViewModel>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.VariantName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CategoryName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.InStock)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AlertStock)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.VariantName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CategoryName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.InStock)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AlertStock)
            </td>
            <td>
                <div class="btn-group btn-group-sm btn-group-solid">
                    <button type="button" class="btn btn-action btn-edit btn-warning" data-id="@item.ID"><span class="glyphicon glyphicon-edit" aria-hidden="true"></span></button>
                    <button type="button" class="btn btn-action btn-details btn-success" data-id="@item.ID"><span class="glyphicon glyphicon-th-list" aria-hidden="true"></span></button>
                    <button type="button" class="btn btn-action btn-delete btn-danger" data-id="@item.ID"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span></button>
                </div>
            </td>
        </tr>
    }
</table>

<script type="text/javascript">
    $(".btn-edit").click(
    function () {
        var vid = $(this).attr("data-id");
        //alert('Masuk : ' + vid);
        $.ajax({
            url: '@Url.Action("Edit", "Items")',
            data: { id: vid },
            type: 'get',
            success: function (result) {
                $(".modal-body").html(result);
                $("#modal-form").modal("show");
            }
        });
    }
);
</script>